language: python
python:
  - "3.6"      # current default Python on Travis CI

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - pylint src
  - pylint tests
  - python -m pytest -rA
  - py.test  --cov-report term --cov=src/

# env:
#  - CODECOV_TOKEN=<token>#IF ONLY YOU HAVE A PRIVATE REPOSITORY

after_success:
  - codecov
